//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_liv_hol_data_holyday_marking
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Holiday { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string InputerID { get; set; }
        public string AuthorizerID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> InputStatus { get; set; }
    }
}
