//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KDMDB : DbContext
    {
        public KDMDB()
            : base("name=KDMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<hr_liv_hol_data_holyday_marking> hr_liv_hol_data_holyday_marking { get; set; }
        public virtual DbSet<tbl_actions> tbl_actions { get; set; }
        public virtual DbSet<tbl_address> tbl_address { get; set; }
        public virtual DbSet<tbl_address_types> tbl_address_types { get; set; }
        public virtual DbSet<tbl_attendance> tbl_attendance { get; set; }
        public virtual DbSet<tbl_attendance_devices> tbl_attendance_devices { get; set; }
        public virtual DbSet<tbl_children> tbl_children { get; set; }
        public virtual DbSet<tbl_city> tbl_city { get; set; }
        public virtual DbSet<tbl_company> tbl_company { get; set; }
        public virtual DbSet<tbl_config> tbl_config { get; set; }
        public virtual DbSet<tbl_contact_person> tbl_contact_person { get; set; }
        public virtual DbSet<tbl_controllers> tbl_controllers { get; set; }
        public virtual DbSet<tbl_country> tbl_country { get; set; }
        public virtual DbSet<tbl_departments> tbl_departments { get; set; }
        public virtual DbSet<tbl_designation> tbl_designation { get; set; }
        public virtual DbSet<tbl_device_data_history> tbl_device_data_history { get; set; }
        public virtual DbSet<tbl_district> tbl_district { get; set; }
        public virtual DbSet<tbl_division> tbl_division { get; set; }
        public virtual DbSet<tbl_education> tbl_education { get; set; }
        public virtual DbSet<tbl_employee_group> tbl_employee_group { get; set; }
        public virtual DbSet<tbl_employee_status> tbl_employee_status { get; set; }
        public virtual DbSet<tbl_employees> tbl_employees { get; set; }
        public virtual DbSet<tbl_factory> tbl_factory { get; set; }
        public virtual DbSet<tbl_file> tbl_file { get; set; }
        public virtual DbSet<tbl_job_details> tbl_job_details { get; set; }
        public virtual DbSet<tbl_job_status> tbl_job_status { get; set; }
        public virtual DbSet<tbl_joining_details> tbl_joining_details { get; set; }
        public virtual DbSet<tbl_menu_category> tbl_menu_category { get; set; }
        public virtual DbSet<tbl_modules> tbl_modules { get; set; }
        public virtual DbSet<tbl_notification> tbl_notification { get; set; }
        public virtual DbSet<tbl_pay_type> tbl_pay_type { get; set; }
        public virtual DbSet<tbl_phone> tbl_phone { get; set; }
        public virtual DbSet<tbl_phone_types> tbl_phone_types { get; set; }
        public virtual DbSet<tbl_police_station> tbl_police_station { get; set; }
        public virtual DbSet<tbl_religions> tbl_religions { get; set; }
        public virtual DbSet<tbl_RoleActionMappings> tbl_RoleActionMappings { get; set; }
        public virtual DbSet<tbl_RoleActions> tbl_RoleActions { get; set; }
        public virtual DbSet<tbl_sections> tbl_sections { get; set; }
        public virtual DbSet<tbl_subsection> tbl_subsection { get; set; }
        public virtual DbSet<tbl_training> tbl_training { get; set; }
        public virtual DbSet<tbl_training_status> tbl_training_status { get; set; }
        public virtual DbSet<tbl_user_defaults> tbl_user_defaults { get; set; }
        public virtual DbSet<tbl_members> tbl_members { get; set; }
    }
}
