//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendance
    {
        public long Id { get; set; }
        public int DeviceID { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<bool> InOut { get; set; }
        public Nullable<int> SwipeNo { get; set; }
        public int ProcessedStatus { get; set; }
        public Nullable<System.DateTime> AttnDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
    }
}
