//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_joining_details
    {
        public long Id { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Designation { get; set; }
        public string BasicSalary { get; set; }
        public string Shift { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public Nullable<System.DateTime> ProbitionPeriodStartDate { get; set; }
        public Nullable<System.DateTime> ProbitionPeriodEndDate { get; set; }
        public string BankName { get; set; }
        public string BankAccountName { get; set; }
        public string Passport_ { get; set; }
        public string TIN { get; set; }
        public string BankAccount_ { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public string ResignationReason { get; set; }
        public string Remarks { get; set; }
    }
}
