//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job_details
    {
        public long ID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> PromotionDate { get; set; }
        public string PreviousDesignation { get; set; }
        public string CurrentDesignation { get; set; }
        public Nullable<System.DateTime> PreviousDesignationStartDate { get; set; }
        public Nullable<System.DateTime> PreviousDesignationEndDate { get; set; }
        public string Status { get; set; }
    }
}
