//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_education
    {
        public int ID { get; set; }
        public string EmployeeId { get; set; }
        public string Exam { get; set; }
        public string InstituteName { get; set; }
        public string BoardName { get; set; }
        public string UniversityName { get; set; }
        public string Duration { get; set; }
        public string PassYear { get; set; }
        public string Class { get; set; }
        public string CGPA { get; set; }
        public string MaxCGPA { get; set; }
        public string GroupName { get; set; }
        public string SubjectName { get; set; }
        public string Remarks { get; set; }
    }
}
