//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_device_data_history
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> AttnDate { get; set; }
        public Nullable<System.DateTime> mDate { get; set; }
        public string mTime { get; set; }
        public string DeviceID { get; set; }
    }
}
