//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendance_devices
    {
        public int id { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Port { get; set; }
        public string Location { get; set; }
    }
}
